name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies (Client)
        run: |
          cd client
          npm install
      - name: Install Dependencies (Server)
        run: |
          cd server
          npm install
      - name: Build Client
        run: |
          cd client
          npm run build
      - name: Build Server
        run: |
          cd server
          npm run build
      - name: Run Tests (Client)
        run: |
          cd client
          npm test
      - name: Run Tests (Server)
        run: |
          cd server
          npm test 